name: CI/CD y Cypress E2E Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: 游닌 Descargar el c칩digo
        uses: actions/checkout@v4

      - name: 游댢 Configurar Node
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: 游닍 Instalar dependencias
        run: npm install

      - name: 游빍 Correr tests con coverage
        run: npm run test -- --coverage
  
  cypress-run:
    runs-on: ubuntu-latest
    needs: ci
    strategy:
      fail-fast: false
      matrix:
        containers: ["cnt-1","cnt-2"]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          start: npm run dev
          wait-on: 'http://localhost:5173'
          record: true
          parallel: true
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
  
  deploy:
    runs-on: ubuntu-latest
    needs: cypress-run
    steps:
      - name: 游닌 Descargar el c칩digo
        uses: actions/checkout@v4

      - name: Deploy to production
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: ${{ secrets.RENDER_SERVICE_ID }}
          api-key: ${{ secrets.RENDER_API_KEY }}
  
  